use clap::{Parser, Subcommand};
use iroh_usbip::{list_physical_devices, UsbDevice, UsbDeviceHandle};

#[derive(Parser, Debug)]
#[command(name = "iroh-usbip", version, about = "Secure P2P USB-over-IP")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// List local physical USB devices connected to the host
    List,

    /// Share a physical USB device securely using a connection ticket
    Share {
        /// Select device by Vendor ID (hex format, e.g., 1d6b)
        #[arg(long)]
        vid: Option<String>,

        /// Select device by Product ID (hex format, e.g., 0002)
        #[arg(long)]
        pid: Option<String>,

        /// Select device by Bus ID
        #[arg(long)]
        bus_id: Option<u8>,

        /// Select device by Device Address
        #[arg(long)]
        address: Option<u8>,
    },

    /// Attach a remote shared USB device as a local virtual USB device
    Attach {
        /// The secure connection ticket generated by the host
        ticket: String,
    },
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::List => {
            let devices = list_physical_devices()?;
            if devices.is_empty() {
                println!("No USB devices found.");
                return Ok(());
            }

            for dev in devices {
                let bus = dev.bus_number();
                let addr = dev.address();
                let desc = match dev.device_descriptor() {
                    Ok(d) => d,
                    Err(e) => {
                        eprintln!("Warning: Failed to get descriptor for device on Bus {} Addr {}: {}", bus, addr, e);
                        continue;
                    }
                };

                let mut manufacturer = None;
                let mut product = None;

                match dev.open() {
                    Ok(handle) => {
                        if desc.manufacturer_string_index.is_some() {
                            manufacturer = handle.read_manufacturer_string(&desc).ok();
                        }
                        if desc.product_string_index.is_some() {
                            product = handle.read_product_string(&desc).ok();
                        }
                    }
                    Err(_) => {
                        // Permission denied or device busy. Indicate this if indices are present.
                        if desc.manufacturer_string_index.is_some() {
                            manufacturer = Some("<Access Denied>".to_string());
                        }
                        if desc.product_string_index.is_some() {
                            product = Some("<Access Denied>".to_string());
                        }
                    }
                }

                let details = match (manufacturer, product) {
                    (Some(m), Some(p)) => format!("{} {}", m, p),
                    (Some(m), None) => m,
                    (None, Some(p)) => p,
                    (None, None) => String::new(),
                };

                if details.is_empty() {
                    println!(
                        "Bus {:03} Device {:03}: ID {:04x}:{:04x}",
                        bus, addr, desc.vendor_id, desc.product_id
                    );
                } else {
                    println!(
                        "Bus {:03} Device {:03}: ID {:04x}:{:04x} {}",
                        bus, addr, desc.vendor_id, desc.product_id, details
                    );
                }
            }
        }
        Commands::Share { vid, pid, bus_id, address } => {
            println!("Placeholder: Sharing USB device...");
            println!("Filter options: VID={:?}, PID={:?}, Bus={:?}, Address={:?}", vid, pid, bus_id, address);
        }
        Commands::Attach { ticket } => {
            println!("Placeholder: Attaching remote USB device using ticket: {}", ticket);
        }
    }

    Ok(())
}
