use clap::{Parser, Subcommand};
use iroh_usbip::{HostDeviceRegistry, DeviceQuery};
use std::sync::Arc;
use iroh::{Endpoint, endpoint::presets};
use iroh_tickets::{Ticket, endpoint::EndpointTicket};

struct IrohStream {
    recv: iroh::endpoint::RecvStream,
    send: iroh::endpoint::SendStream,
}

impl tokio::io::AsyncRead for IrohStream {
    fn poll_read(
        mut self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
        buf: &mut tokio::io::ReadBuf<'_>,
    ) -> std::task::Poll<std::io::Result<()>> {
        std::pin::Pin::new(&mut self.recv).poll_read(cx, buf)
    }
}

impl tokio::io::AsyncWrite for IrohStream {
    fn poll_write(
        mut self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
        buf: &[u8],
    ) -> std::task::Poll<std::io::Result<usize>> {
        match std::pin::Pin::new(&mut self.send).poll_write(cx, buf) {
            std::task::Poll::Ready(res) => std::task::Poll::Ready(res.map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e))),
            std::task::Poll::Pending => std::task::Poll::Pending,
        }
    }

    fn poll_flush(
        mut self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<std::io::Result<()>> {
        match std::pin::Pin::new(&mut self.send).poll_flush(cx) {
            std::task::Poll::Ready(res) => std::task::Poll::Ready(res.map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e))),
            std::task::Poll::Pending => std::task::Poll::Pending,
        }
    }

    fn poll_shutdown(
        mut self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<std::io::Result<()>> {
        match std::pin::Pin::new(&mut self.send).poll_shutdown(cx) {
            std::task::Poll::Ready(res) => std::task::Poll::Ready(res.map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e))),
            std::task::Poll::Pending => std::task::Poll::Pending,
        }
    }
}

#[derive(Parser, Debug)]
#[command(name = "iroh-usbip", version, about = "Secure P2P USB-over-IP")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// List local physical USB devices connected to the host
    List,

    /// Share a physical USB device securely using a connection ticket
    Share {
        /// Select device by Vendor ID (hex format, e.g., 1d6b)
        #[arg(long)]
        vid: Option<String>,

        /// Select device by Product ID (hex format, e.g., 0002)
        #[arg(long)]
        pid: Option<String>,

        /// Select device by Bus ID
        #[arg(long)]
        bus_id: Option<u8>,

        /// Select device by Device Address
        #[arg(long)]
        address: Option<u8>,
    },

    /// Attach a remote shared USB device as a local virtual USB device
    Attach {
        /// The secure connection ticket generated by the host
        ticket: String,
    },
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::List => {
            let registry = HostDeviceRegistry::new_physical()?;
            let devices = registry.find_devices(&DeviceQuery::default())?;
            if devices.is_empty() {
                println!("No USB devices found.");
                return Ok(());
            }

            for dev in devices {
                println!("{}", dev.cli_info);
            }
        }
        Commands::Share { vid, pid, bus_id, address } => {
            let registry = HostDeviceRegistry::new_physical()?;
            let query = DeviceQuery::from_cli_args(
                vid.as_deref(),
                pid.as_deref(),
                bus_id,
                address,
            )?;
            let matched = registry.find_single_device(&query)?;
            let dev = matched.device;

            println!("Sharing USB device {}...", matched.cli_info);

            // Initialize Iroh Node
            let endpoint = Endpoint::builder(presets::N0)
                .alpns(vec![b"iroh-usbip".to_vec()])
                .bind()
                .await?;

            let addr = endpoint.addr();
            let ticket = EndpointTicket::new(addr.clone());
            println!("Connection ticket:\n{}", ticket.encode_string());

            println!("Waiting for client to connect...");
            if let Some(incoming) = endpoint.accept().await {
                let conn = incoming.await?;
                println!("Client connected! Establishing stream...");
                let (send, recv) = conn.accept_bi().await?;
                let stream = IrohStream { send, recv };
                println!("Session started. Redirecting USB traffic.");
                let static_registry = HostDeviceRegistry::new_static(vec![Arc::clone(&dev)]);
                if let Err(e) = iroh_usbip::engine::run_usbip_session(stream, Arc::new(static_registry)).await {
                    eprintln!("Session error: {}", e);
                }
                println!("Session ended. Detaching client.");
            }

            endpoint.close().await;
        }
        Commands::Attach { ticket: ticket_str } => {
            let ticket = EndpointTicket::decode_string(&ticket_str)?;
            let endpoint = Endpoint::bind(presets::N0).await?;

            let local_addr = "127.0.0.1:3240";
            let listener = tokio::net::TcpListener::bind(local_addr).await?;
            println!("Local proxy listening on tcp://{}...", local_addr);
            println!("Connecting to remote shared device via Iroh P2P...");

            let conn: iroh::endpoint::Connection = endpoint.connect(ticket.endpoint_addr().clone(), b"iroh-usbip").await?;
            println!("Connected to Host! Tunnel established. Press Ctrl+C to disconnect.");

            // Accept local TCP connections
            while let Ok((mut tcp_stream, peer_addr)) = listener.accept().await {
                println!("Local client connected: {}", peer_addr);
                let (send, recv) = conn.open_bi().await?;
                let mut iroh_stream = IrohStream { send, recv };

                tokio::spawn(async move {
                    if let Err(e) = tokio::io::copy_bidirectional(&mut tcp_stream, &mut iroh_stream).await {
                        eprintln!("Proxy forward error: {}", e);
                    }
                    println!("Local client disconnected: {}", peer_addr);
                });
            }

            endpoint.close().await;
        }
    }

    Ok(())
}
