name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Lix (Nix)
        uses: samueldr/lix-gha-installer-action@v1

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run hermetic checks
        run: nix flake check

      - name: Run E2E Integration Tests
        run: |
          nix develop --command bash -c "IROH_USBIP_MOCK=1 scripts/e2e.sh"
